version: '3'
services:
  db:
    image: "postgres"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
  app:
    build:
      context: .
      dockerfile: compose/Dockerfile
    volumes:
      - .:/app
    stdin_open: true
    env_file:
      - task_fast_api/.env
    ports:
      - "8000:8000"
    command: python main.py
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.ru
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "9713:80"
    logging:
      driver: none
    restart: always

volumes:
  database-data: { } # named volumes can be managed easier using docker-compose
  pgadmin: