"""Delete is_superuser

Revision ID: e8079c0a1146
Revises: 47f4d977a13a
Create Date: 2021-07-30 13:18:39.722741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8079c0a1146'
down_revision = '47f4d977a13a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_superuser')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
